"""sync_schema_updates

Revision ID: 2940f5ddde82
Revises: d3e4f5a6b7c8
Create Date: 2026-02-28 19:55:02.618823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '2940f5ddde82'
down_revision: Union[str, None] = 'd3e4f5a6b7c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_embeddings_item_id'), table_name='item_embeddings')
    op.drop_table('item_embeddings')
    op.add_column('items', sa.Column('purchase_price', sa.Float(), nullable=True))
    op.add_column('items', sa.Column('current_trip_id', app.models.compatibility.GUID(), nullable=True))
    op.alter_column('items', 'id',
               existing_type=sa.NUMERIC(),
               type_=app.models.compatibility.GUID(),
               existing_nullable=False)
    op.alter_column('items', 'current_location_id',
               existing_type=sa.NUMERIC(),
               type_=app.models.compatibility.GUID(),
               existing_nullable=False)
    op.alter_column('items', 'permanent_location_id',
               existing_type=sa.NUMERIC(),
               type_=app.models.compatibility.GUID(),
               existing_nullable=True)
    op.create_index(op.f('ix_items_current_trip_id'), 'items', ['current_trip_id'], unique=False)
    op.create_foreign_key(None, 'items', 'trips', ['current_trip_id'], ['id'], ondelete='SET NULL')
    op.alter_column('locations', 'id',
               existing_type=sa.NUMERIC(),
               type_=app.models.compatibility.GUID(),
               existing_nullable=False)
    op.alter_column('locations', 'parent_id',
               existing_type=sa.NUMERIC(),
               type_=app.models.compatibility.GUID(),
               existing_nullable=True)
    op.alter_column('movement_history', 'id',
               existing_type=sa.NUMERIC(),
               type_=app.models.compatibility.GUID(),
               existing_nullable=False)
    op.alter_column('movement_history', 'item_id',
               existing_type=sa.NUMERIC(),
               type_=app.models.compatibility.GUID(),
               existing_nullable=False)
    op.alter_column('movement_history', 'from_location_id',
               existing_type=sa.NUMERIC(),
               type_=app.models.compatibility.GUID(),
               existing_nullable=True)
    op.alter_column('movement_history', 'to_location_id',
               existing_type=sa.NUMERIC(),
               type_=app.models.compatibility.GUID(),
               existing_nullable=False)
    op.alter_column('movement_history', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('outfits', 'id',
               existing_type=sa.NUMERIC(),
               type_=app.models.compatibility.GUID(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('outfits', 'id',
               existing_type=app.models.compatibility.GUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('movement_history', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('movement_history', 'to_location_id',
               existing_type=app.models.compatibility.GUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('movement_history', 'from_location_id',
               existing_type=app.models.compatibility.GUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('movement_history', 'item_id',
               existing_type=app.models.compatibility.GUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('movement_history', 'id',
               existing_type=app.models.compatibility.GUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('locations', 'parent_id',
               existing_type=app.models.compatibility.GUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('locations', 'id',
               existing_type=app.models.compatibility.GUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_index(op.f('ix_items_current_trip_id'), table_name='items')
    op.alter_column('items', 'permanent_location_id',
               existing_type=app.models.compatibility.GUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('items', 'current_location_id',
               existing_type=app.models.compatibility.GUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('items', 'id',
               existing_type=app.models.compatibility.GUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_column('items', 'current_trip_id')
    op.drop_column('items', 'purchase_price')
    op.create_table('item_embeddings',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('item_id', sa.NUMERIC(), nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=1000), nullable=False),
    sa.Column('embedding', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_embeddings_item_id'), 'item_embeddings', ['item_id'], unique=False)
    # ### end Alembic commands ###
