"""Baseline schema

Revision ID: 90abc7f31028
Revises: 
Create Date: 2026-02-11 20:13:15.015992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90abc7f31028'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.Enum('ROOM', 'FURNITURE', 'CONTAINER', 'SURFACE', 'PORTABLE', 'LAUNDRY_WORN', 'LAUNDRY_DIRTY', name='locationkind'), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.Column('qr_code_id', sa.String(length=100), nullable=True),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('is_wardrobe', sa.Boolean(), nullable=False),
    sa.Column('default_clothing_category', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_is_wardrobe'), 'locations', ['is_wardrobe'], unique=False)
    op.create_index(op.f('ix_locations_name'), 'locations', ['name'], unique=False)
    op.create_index(op.f('ix_locations_parent_id'), 'locations', ['parent_id'], unique=False)
    op.create_index(op.f('ix_locations_qr_code_id'), 'locations', ['qr_code_id'], unique=True)
    op.create_table('outfits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('item_ids', sa.JSON(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('wear_count', sa.Integer(), nullable=False),
    sa.Column('last_worn_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outfits_name'), 'outfits', ['name'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('current_location_id', sa.UUID(), nullable=False),
    sa.Column('permanent_location_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('is_temporary_placement', sa.Boolean(), nullable=False),
    sa.Column('last_moved_at', sa.DateTime(), nullable=True),
    sa.Column('qr_code_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('item_type', sa.Enum('GENERIC', 'CLOTHING', name='itemtype'), nullable=False),
    sa.Column('item_data', sa.JSON(), nullable=True),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('is_lent', sa.Boolean(), nullable=False),
    sa.Column('lent_to', sa.String(length=255), nullable=True),
    sa.Column('lent_at', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('lent_notes', sa.String(length=500), nullable=True),
    sa.Column('is_lost', sa.Boolean(), nullable=False),
    sa.Column('lost_at', sa.DateTime(), nullable=True),
    sa.Column('lost_notes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['current_location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['permanent_location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_current_location_id'), 'items', ['current_location_id'], unique=False)
    op.create_index(op.f('ix_items_is_lent'), 'items', ['is_lent'], unique=False)
    op.create_index(op.f('ix_items_is_lost'), 'items', ['is_lost'], unique=False)
    op.create_index(op.f('ix_items_item_type'), 'items', ['item_type'], unique=False)
    op.create_index(op.f('ix_items_name'), 'items', ['name'], unique=False)
    op.create_index(op.f('ix_items_permanent_location_id'), 'items', ['permanent_location_id'], unique=False)
    op.create_index(op.f('ix_items_qr_code_id'), 'items', ['qr_code_id'], unique=True)
    op.create_table('movement_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('from_location_id', sa.UUID(), nullable=True),
    sa.Column('to_location_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('PLACED', 'MOVED', 'RETURNED', 'WORN', 'WASHED', 'LENT', 'RETURNED_FROM_LOAN', 'LOST', 'FOUND', name='actiontype'), nullable=False),
    sa.Column('moved_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['from_location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movement_history_item_id'), 'movement_history', ['item_id'], unique=False)
    op.create_index(op.f('ix_movement_history_moved_at'), 'movement_history', ['moved_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movement_history_moved_at'), table_name='movement_history')
    op.drop_index(op.f('ix_movement_history_item_id'), table_name='movement_history')
    op.drop_table('movement_history')
    op.drop_index(op.f('ix_items_qr_code_id'), table_name='items')
    op.drop_index(op.f('ix_items_permanent_location_id'), table_name='items')
    op.drop_index(op.f('ix_items_name'), table_name='items')
    op.drop_index(op.f('ix_items_item_type'), table_name='items')
    op.drop_index(op.f('ix_items_is_lost'), table_name='items')
    op.drop_index(op.f('ix_items_is_lent'), table_name='items')
    op.drop_index(op.f('ix_items_current_location_id'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_outfits_name'), table_name='outfits')
    op.drop_table('outfits')
    op.drop_index(op.f('ix_locations_qr_code_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_parent_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_name'), table_name='locations')
    op.drop_index(op.f('ix_locations_is_wardrobe'), table_name='locations')
    op.drop_table('locations')
    # ### end Alembic commands ###
