"""Fix schema drift

Revision ID: c717eb6ba5a5
Revises: 90abc7f31028
Create Date: 2026-02-11 20:13:38.869703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c717eb6ba5a5'
down_revision: Union[str, None] = '90abc7f31028'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'is_lost',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('items', 'lost_notes',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.drop_constraint('items_qr_code_id_key', 'items', type_='unique')
    op.create_index(op.f('ix_items_is_lost'), 'items', ['is_lost'], unique=False)
    op.create_index(op.f('ix_items_qr_code_id'), 'items', ['qr_code_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_qr_code_id'), table_name='items')
    op.drop_index(op.f('ix_items_is_lost'), table_name='items')
    op.create_unique_constraint('items_qr_code_id_key', 'items', ['qr_code_id'])
    op.alter_column('items', 'lost_notes',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('items', 'is_lost',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###
